### ISSUE TITLE
export the image to png

### ISSUE THREAD

**Issue by cheanney** [ebi-uniprot/ProtVista#1]
How can I write a javascript function to export the image to PNG?

**Comment by xwatkins** [comment]
Unfortunately there is no way to do this at the moment, apart from doing a screen capture. We are looking at the possibility to add SVG download in the future.

**Comment by ljgarcia** [comment]
Duplicated at https://github.com/ebi-uniprot/ProtVista/issues/3
I will close this one as the other includes some more discussion.
