### ISSUE TITLE
multiple viewers on one page

### ISSUE THREAD

**Issue by cheanney** [ebi-uniprot/ProtVista#2]
Hi,

I am trying to have multiple viewers on an accordion. However, the "hide/show" icon only works with the first viewer.  I am wondering if you assist me on how to fix the issue.

Thanks in advance.

Anney

**Comment by xwatkins** [comment]
Hi Anney, 

We initially developed the Feature Viewer so it would only be one per page, as at the time we didn't find any use cases of having multiple instances on the same page (clearly, we were wrong!). However, if all the other functionality (zoom, tooltips, etc...) works fine, adding unique identifiers to the show/hide should be easy for us. Let me know!

All the best,
Xavier

**Comment by cheanney** [comment]
Hi Xavier,

Thank you for your fast reply.
I am use this protein viewer to visualize orthologs on one page.
If this is a quick fix for you, it will be great to have unique identifiers
added.


Thank you for this awesome library!!

Anney

**Comment by ljgarcia** [comment]
Multiple components on the same page were integrated a while ago. Take a look to the snippet two_viewers_example.js
