### ISSUE TITLE
Multiple exclusions issue ?

### ISSUE THREAD

**Issue by salutlespotes** [ebi-uniprot/ProtVista#32]
Hi,
First of all, thank you for this awesome librairy !  I'm trying to use the Feature Viewer to only show  "domains and sites" so, after reading the doc I use this code 
`<div id='yourDiv'/>`
`<script>`
`window.onload = function() {`
`var yourDiv = document.getElementById('yourDiv');`
`var biojs_vis_proteinFeaturesViewer = require('biojs-vis-proteinfeaturesviewer');`
`var instance = new biojs_vis_proteinFeaturesViewer({`
`el: yourDiv,`
`uniprotacc: 'P05067',`
`exclusions: ['MOLECULE_PROCESSING', 'PTM', 'SEQUENCE_INFORMATION', 'STRUTURAL','TOPOLOGY','MUTAGENESIS', 'PROTEOMICS', 'VARIATION']`
`});`
`}`
`</script>`
`</div>`

However, structural features, proteomics and variants (variation) are showed (see attached picture)
![image](https://cloud.githubusercontent.com/assets/20322719/16623630/9540fdec-4396-11e6-96c2-5b8899b4dad6.png)
. 
Do I write something wrong ?

Thank you for your help and sorry for my bad english.

**Comment by ljgarcia** [comment]
Hi there,

The structural features still appear due to a typo in your exclusion 
list. You have '|STRUTURAL|' but it should be '|STRUCTURAL|'.
As for |'PROTEOMICS' and 'VARIATION', you have found a bug! Thanks for 
reporting it. We will work on it and will let you know when it has been 
fixed.

We are glad to know you find useful our component. Sorry about the 
exclusion inconveniences at this time.

Regards,

|On 06/07/2016 16:32, salutlespotes wrote:

**Comment by salutlespotes** [comment]
You are right, thank you !
I noticed and other exclusion issue :  the exclusion of 'DOMAIN_AND_SITES' not seems effective.

Regards,

**Comment by ljgarcia** [comment]
It should be 'DOMAINS_AND_SITES', plural for both, then it should work.
And exclusions of 'PROTEOMICS' and 'VARIATION' should be working now.

Please also note that biojs-vis-proteinFeatureViewer has been re-branded as ProtVista so please do
npm uninstall biojs-vis-proteinFeatureViewer
npm install ProtVista

You will have to instantiate the component as
var myApp = require('ProtVista');

Exclusions should work. Please let us know how it goes for you.
Thanks and sorry for the inconveniences!

**Comment by salutlespotes** [comment]
Hi,

Thank you for your reactivity !
I'm trying to build something as light as possible so I prefer to use the CDN-like way (and I'm also not really familiar with npm ). So I read the new documentation and wrote this code : 
```html
<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <script src="http://ebi-uniprot.github.io/CDN/feature-viewer/featuresviewer.js"></script>
        <!-- <link href="featureviewer.css" rel="stylesheet"/>  custom css-->   
        <link href="http://ebi-uniprot.github.io/CDN/feature-viewer/css/main.css" rel="stylesheet"/>  

        <!--     create  function for each category -->
        <script type="text/javascript">
            function getdomain(uniprotacc) {
                var fv_domain = document.getElementById('fv_domain');
                var ProtVista = require('ProtVista');
                var instance = new ProtVista({
                    el: fv_domain,
                    uniprotacc: uniprotacc,
                    exclusions: ['MOLECULE_PROCESSING','PTM','SEQUENCE_INFORMATION','STRUCTURAL','PROTEOMICS','VARIATION','TOPOLOGY','MUTAGENESIS']
                });
            };

            function getstructural(uniprotacc) {
                var fv_structural = document.getElementById('fv_structural');
                var ProtVista = require('ProtVista');
                var instance = new ProtVista({
                    el: fv_structural,
                    uniprotacc: uniprotacc,
                    exclusions: ['MOLECULE_PROCESSING','PTM','SEQUENCE_INFORMATION','DOMAINS_AND_SITES','PROTEOMICS','VARIATION','TOPOLOGY','MUTAGENESIS']
                });
            };

            function gettopology(uniprotacc) {
                var fv_topology = document.getElementById('fv_topology');
                var ProtVista = require('ProtVista');
                var instance = new ProtVista({
                    el: fv_topology,
                    uniprotacc: uniprotacc,
                    exclusions:             ['DOMAINS_AND_SITES','MOLECULE_PROCESSING', 'PTM', 'SEQUENCE_INFORMATION',   'STRUCTURAL','MUTAGENESIS','PROTEOMICS', 'VARIATION' ]
                });
            };
        </script>


        <!-- multiple onload -->
        <script type="text/javascript">

        function addEvent(obj, event, fct) {
        if (obj.attachEvent) //Est-ce IE ?
            obj.attachEvent("on" + event, fct); //Ne pas oublier le "on"
        else
            obj.addEventListener(event, fct, true);
        };

        function lancer(fct) {
            addEvent(window, "load", fct);     
        };
        </script>
    </head>

    <body>

        <div id='fv_domain'/>
            <script>
            lancer(getdomain('P05067'));
            </script>
        </div>

        <div id='fv_structural'/>
            <script>
            lancer(getstructural('P05067'));
            </script>
        </div>

        <div id='fv_topology'/>
            <script>
            lancer(gettopology('P05067'));
            </script>
        </div>
        
    </body>
</html>
```

But it doesn't seems to be working and I really don(t know why. With the previous version it's was, a least, partially working. I hope you can help me to find where my code is wrong.

Thank you per advance,

Regards

**Comment by ljgarcia** [comment]
Hi there, 

Nothing wrong with your code, problem is in our end. Please give us one day more, it should be working tomorrow.

Cheers!

**Comment by salutlespotes** [comment]
Hi,
Nice !  I look forward to try that :) 

Have a nice day !

**Comment by ljgarcia** [comment]
Hi, 

We have updated the documentation, please use 
```
<script src="http://ebi-uniprot.github.io/CDN/protvista/protvista.js"></script>
<link href="http://ebi-uniprot.github.io/CDN/protvista/css/main.css" rel="stylesheet"/>   
```

I noticed you have multiple instances of the component, I am afraid that is not currently supported, you will have problems with the zooming and selection, see https://github.com/ebi-uniprot/ProtVista/issues/2. We are already working on it and should be ready pretty soon, we appreciate your patience.

Please do let us know how it works with the exclusions.

Cheers,

**Comment by ljgarcia** [comment]
By the way, the documentation is available at http://ebi-uniprot.github.io/ProtVista/

**Comment by salutlespotes** [comment]
Hi,
It's completely functional ! Thank you so much.
Concerning the multiples instances you are right it's  bit buggy when I try to zoom in/out.

Regards,

**Comment by ljgarcia** [comment]
Good to know! I will close this issue now, but please keep an eye on the other thread, https://github.com/ebi-uniprot/ProtVista/issues/2, as the fix is coming soon.
