### ISSUE TITLE
example.html:9 Uncaught TypeError: ProtVista.hello is not a function(anonymous function) 

### ISSUE THREAD

**Issue by ramakrishnas** [ebi-uniprot/ProtVista#37]
Hi,

I'm trying to test ProtVista, example.html, but is giving me the following error.

example.html:9 Uncaught TypeError: ProtVista.hello is not a function(anonymous function) @ example.html:9

**Comment by ljgarcia** [comment]
Hi @ramakrishnas 

Please give it a try again, I just fixed the bug, please do let us know how it works. Glad you are interested in our viewer.
