### ISSUE TITLE
Document how to add custom/non-uniprot source data

### ISSUE THREAD

**Issue by JervenBolleman** [ebi-uniprot/ProtVista#5]
Currently there seems to be one data-source. It would be nice to be able to use other datasources if needed. Could you add some documentation/examples on how to do so.

**Comment by sillitoe** [comment]
++

Agree - would be great to add extra tracks for local data sources.

**Comment by ljgarcia** [comment]
We are working on it. Already got some requirements and soon working on implementation. If you have a use case it would be great to hear about it!

**Comment by sillitoe** [comment]
Sounds great - thanks for the update. 

A few possibilities come immediately to mind that would be very useful for us (CATH):

 * adding region based annotations (e.g. for our own structural domains)
 * adding residue-based annotations (e.g. show catalytic site information inherited through a sequence alignment)

Happy to help with testing / developing.

**Comment by Nilesh-Meharkar** [comment]
Thanks, ProtVista team!!..   . 
for such an awesome representation of Protein domain UI.
My team is totally impressed with your user interface, in our project we want to display same UI for our own protein data, can you please help me with it, to support ProtVista with different data-source than uniprot data.

Our team is too much interested in contribution to this project.

Thanks,

**Comment by ljgarcia** [comment]
Hi Nilesh, all,

Thanks for your comments. We are currently working on this functionality. We would be grateful if you can provide a bit more information.
* What kind of features would you like to include?
* What format can you provide your data on?
* Do you have own data for variants? If so, do you have any color scheme to distinguish, let's say deleterious from benign? Or would you be happy with the currently consequence color assign by the viewer?
* Would you like to start the viewer with your own data and display it on your own page? Or would you like to upload your data to a viewer already available on a web site?

Many thanks!

**Comment by Nilesh-Meharkar** [comment]
Hi ljgarcia,

      Thanks, for quick reply.
I will get back to you, after discussing with my team with finalized requirements.
thanks!.. .

**Comment by ljgarcia** [comment]
It has been out for a bit now but documentation is still not visible, it will be soon. By now, here is the link http://ebi-uniprot.github.io/ProtVista/dataServicesAndFormat.html
