### ISSUE TITLE
Possible Feature: plotting vector of residue-level values

### ISSUE THREAD

**Issue by malcook** [ebi-uniprot/ProtVista#57]
As an application developer I wish to display my bespoke residue-level protein sequence analysis results in the context of uniprot feature annotations.  

This might be considered analogous the Javascript JBrowse genome viewer support for [Wiggle/BigWig Tracks \(XYPlot, Density\)](http://gmod.org/wiki/JBrowse_Configuration_Guide#Wiggle.2FBigWig_Tracks_.28XYPlot.2C_Density.29)

I am unsure whether the appropriate container for values to display could profitably be the  .wig or .bigwig files conventionally used in genomics.   Is there a standard such format in protein analysis? Not using wig/bigwig would lose the advantage of http byte-range requests - though I expect this is much less important consideration as proteins are much smaller 

One appealing feature of the JBrowse approach is the UrlTemplate which if adopted by ProtVista might allow interpolating the value of uniprotacc while instantiating the URL.

**Comment by xwatkins** [comment]
Hi @malcook, 

This version of ProtVista is now only under maintenance as we are developing a new version as web components here: https://github.com/ebi-webcomponents

This new version separates the data loaders from the tracks, which means it should be possible to write a `wig-data-loader` component and `wig-data-adapter` (parser) component as well as a `protvista-density-track`. BigWig being a binary format, it would be more difficult to handle and likely require server-side processing.

Could you create the same issue here, so we can keep track of your user story? https://github.com/ebi-webcomponents/project

Thanks,
Xav

**Comment by malcook** [comment]
Happy to oblige.  See:  https://github.com/ebi-webcomponents/project/issues/9
